[package]
name = "gotham-middleware-jwt"
version = "0.1.0"
authors = ["Nicholas Young <nyoung@uptime.ventures>"]

[dependencies]
futures = "0.1"
gotham = { git = "https://github.com/gotham-rs/gotham", branch = "master" }
serde = "1.0"
serde_derive = "1.0.69"
hyper = "0.11"
jsonwebtoken = "4.0"
log = "0.4.3"
